#!/bin/bash

# panel setup
PANEL_HEIGHT=18
PANEL_FONT_FAMILY=
PANEL_FONT_FAMILY="$PANEL_FONT_FAMILY,-*-stlarch-medium-r-*-*-10-*-*-*-*-*-*-*"
PANEL_FONT_FAMILY="$PANEL_FONT_FAMILY,-*-lemon-*-*-*-*-10-*-*-*-*-*-*-*"
#PANEL_FONT_FAMILY="$PANEL_FONT_FAMILY,-*-proggytiny-*-*-*-*-*-*-*-*-*-*-*-*"

[ -f /tmp/xrandr.txt ] || xrandr > /tmp/xrandr.txt

mon_dimensions=$(cat /tmp/xrandr.txt | grep primary | awk '{ print $4 }')
mon_offset=$(echo $mon_dimensions | cut -d+ -f2)
mon_width=$(echo $mon_dimensions | cut -dx -f1)

PANEL_GEOMETRY="$((mon_width - 18))x${PANEL_HEIGHT}+$((mon_offset + 9))+9"
#PANEL_GEOMETRY=$(echo $mon_dimensions | sed 's/x[0-9]\+/x'$PANEL_HEIGHT'/')

PANEL_FIFO=/tmp/panel-fifo

# colors
C_FG="#FF$(grep '*foreground:' ~/.Xresources | cut -d'#' -f2)"
C_BG="#FF$(grep '*background:' ~/.Xresources | cut -d'#' -f2)"
#C_FOC="#FF$(grep '*color2:' ~/.Xresources   | cut -d'#' -f2)"
C_URG="#FF$(grep '*color1:' ~/.Xresources   | cut -d'#' -f2)"
C_FOC='#FF0088CC'
#C_URG='#FF992211'
