#!/bin/bash

# Note: to get the mouse coordinates in variables X and Y:
# eval $(xdotool getmouselocation --shell)

pkill -x dmenu

if [ $(pgrep -cf conky_$1) -gt 0 ]; then
    if [ -n "$(xdotool search --onlyvisible --class conky_$1)" ]; then
        xdotool search --class conky windowunmap %@
    else
        xdotool search --class conky windowunmap %@
        xdotool search --class conky_$1 windowmap %1 windowraise
    fi
else
    source ~/.config/bspwm/panel/config
    screen_width=$(cat /tmp/xrandr.txt | grep -o 'current [0-9]\+' | awk '{print $2}')

    xdotool search --class conky windowunmap %@
    if [ "$1" == 'cal' ]; then
        # centered, use alignment top_middle in conkyrc
        # NOTE: top_middle alone doesn't work with multiple screens of different pixel widths
        pos=$(((mon_offset + (mon_width - screen_width) / 2) * -1 ))
        conky -x "$pos" -c ~/.config/bspwm/panel/conky/conky_$1
    elif [ "$1" == 'weather' ]; then
        google-chrome-stable 'https://www.google.com/#q=weather'
    else
        # right-aligned, use alignment top_right in conkyrc
        pos=$((screen_width - (mon_width + mon_offset - 16)))
        conky -x "$pos" -c ~/.config/bspwm/panel/conky/conky_$1
    fi
fi
