#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources

[[ -f ~/.bin/displays.sh ]] && source ~/.bin/displays.sh

if [[ "$1" == bspwm ]]; then
    sxhkd &
    xsetroot -cursor_name left_ptr
    # store xrandr output for faster access
    xrandr > /tmp/xrandr.txt
fi

xset +fp /usr/share/fonts/local
xset +fp ~/.fonts
xset fp rehash

exec $1
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
