#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#
# See also:
# https://wiki.archlinux.org/index.php/Xprofile

[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile

exec startxfce4
# exec gnome-session
# exec startkde
# ...or the Window Manager of your choice

