[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock"]
language-servers = [
  { name = "pyright" },
]
