[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py"]
rulers = [100]
language-servers = [
  { name = "ty" },
  #{ name = "pyright" },
]

[language-server.pyright]
command = "basedpyright-langserver"

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ty.config]
inlayHints.callArgumentNames = false
experimental.rename = true
experimental.autoImport = true
