#!/bin/bash

bspc config border_width    2
bspc config window_gap      9

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true
bspc config remove_unplugged_monitors  true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc config focused_border_color "$(xrdb -query | grep foreground | awk '{ print $2 }')"
bspc config normal_border_color  "$(xrdb -query | grep background | awk '{ print $2 }')"

[ -f ~/.config/bspwm/bspc_setup_monitors.sh ] && ~/.config/bspwm/bspc_setup_monitors.sh
bspc config -m primary top_padding 20

bspc rule -a Gimp-2.8 state=floating follow=on
bspc rule -a Gnome-calendar state=floating follow=on

xsetroot -cursor_name left_ptr
[ -f ~/.fehbg ] && source ~/.fehbg
[ -f ~/.config/bspwm/startup.sh ] && ~/.config/bspwm/startup.sh
