#!/bin/bash
{
export SXHKD_SHELL='/usr/bin/sh'

bspc config border_width    2
bspc config window_gap      9

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true
bspc config remove_unplugged_monitors  true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true

fg_color=$(xrdb -query | grep -m1 foreground | awk '{ print $2 }')
bg_color=$(xrdb -query | grep -m1 background | awk '{ print $2 }')

bspc config focused_border_color  "$fg_color"
bspc config presel_feedback_color "$fg_color"
bspc config normal_border_color   "$bg_color"
bspc config active_border_color   "$bg_color"

bspc rule -a Orage state=floating follow=on
bspc rule -a Matplotlib state=floating follow=on

xsetroot -cursor_name left_ptr
xset s 300 # blank screen after N seconds of inactivity
xset +dpms # enable DPMS
xset dpms 600 600 0 # trigger display {standby, suspend, off} after N seconds of inactivity

[ -f ~/.config/bspwm/bspc_setup_monitors.sh ] && ~/.config/bspwm/bspc_setup_monitors.sh

# Annoyingly, the -d arg below doesn't take effect until after it finds a config file.
# I.e. you can't use -d to tell supervisord where to look for a config.
[ -f ~/.config/bspwm/supervisord.conf ] && supervisord -d ~/.config/bspwm/ -c ~/.config/bspwm/supervisord.conf

} &> /tmp/bspwmrc.log
