#!/bin/bash

bspc config border_width    2
bspc config window_gap      9

bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config focus_follows_pointer      true
bspc config pointer_follows_monitor    true
bspc config remove_unplugged_monitors  true
bspc config remove_disabled_monitors   true
bspc config remove_unplugged_monitors  true
bspc config merge_overlapping_monitors true

bspc config focused_border_color "$(xrdb -query | grep foreground | awk '{ print $2 }')"
bspc config normal_border_color  "$(xrdb -query | grep background | awk '{ print $2 }')"

xrandr --output eDP-1 --primary

[ -f ~/.config/bspwm/bspc_setup_monitors.sh ] && ~/.config/bspwm/bspc_setup_monitors.sh

bspc rule -a Gimp follow=on floating=on

xsetroot -cursor_name left_ptr
[ -f ~/.config/bspwm/startup.sh ] && ~/.config/bspwm/startup.sh
