#! /usr/bash
#
# Aliases
#

alias ls='ls --color=auto'
alias ll='ls -Alh'

alias cls='clear; ls'

#alias tmux='tmux -2'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias src='source ~/.bash_profile'
alias functions='vim ~/.bash/functions'
alias aliases='vim ~/.bash/aliases'
alias startup='vim ~/.bash/init.sh'
alias paths='vim ~/.bash/path'
alias vars='vim ~/.bash/vars'

alias brc='vim ~/.bashrc'
alias bprof='vim ~/.bash_profile'
alias vrc='vim ~/.vimrc'
alias tconf='vim ~/.tmux.conf'

# apt/dpkg shortcuts
alias pkg-stat='dpkg --get-selections | grep'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# URL-encode strings
alias urlencode='python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1]);"'

# View HTTP traffic
alias sniff="sudo ngrep -d 'eth0' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i eth0 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Get week number
alias week='date +%V'

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

