#! /bin/bash
#
# Functions
#

cl()
{
    clear; cd $@; ls
}

cltest()
{
    RET="`cd $1`"
    if [ "$RET" ]; then
        echo "cd returned: \"$RET\""
    else
        cd $1; ls
    fi
}


# Determine size of a file or total size of a directory
function fs() {
    if du -b /dev/null > /dev/null 2>&1; then
        local arg=-sbh
    else
        local arg=-sh
    fi
    if [[ -n "$@" ]]; then
        du $arg -- "$@"
    else
        du $arg .[^.]* *
    fi
}

shparproc()
{
    cat /proc/$PPID/status | head -1 | cut -f2
}

# change extensions for all files in the current directory
# $1 = extension to be changed
# $2 = new extension
# NOTE: must include '.' in both $1 and $2
chext()
{
    for f in *$1; do
        name=`echo $f | cut -d . -f 1`
        new=$name$2
        mv -i $f $new
    done
}

cmd-exists()
{
    type $1 &> /dev/null
}

gui2pid()
{
    xprop _NET_WM_PID | sed 's/_NET_WM_PID(CARDINAL) = //' | ps `cat`
}

