#!/bin/bash

bspc config border_width    2
bspc config window_gap      9

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
#bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config focused_border_color "#0088cc"
bspc config normal_border_color "$(xrdb -query | grep background | awk '{ print $2 }')"

for monitor in $(bspc query -M); do
    case "$monitor" in
        LVDS-0)
            num=1
            ;;
        DP-3)
            num=2
            ;;
        DP-5)
            num=3
            ;;
        *)
            num=
    esac
    if [ -n "$num" ]; then
        bspc monitor "$monitor" -n "$num" -d "$num"/{1,2,3,4,5}
    else
        bspc monitor "$monitor" -d {1,2,3,4,5}
    fi
done

bspc rule -a Gimp follow=on floating=on
bspc rule -a Screenkey manage=off
bspc rule -a Synapse manage=off

[ -f ~/.fehbg ] && source ~/.fehbg
xsetroot -cursor_name left_ptr
[ -f ~/.config/bspwm/startup.sh ] && ~/.config/bspwm/startup.sh

