#! /bin/sh

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

#bspc config focused_border_color "#0088cc"
bspc config focused_border_color "#c5c8c6"

i=1
for monitor in $(bspc query -M); do
    case $monitor in
        LVDS-1)
            num=1
            ;;
        DP-1)
            num=2
            ;;
        DP-3)
            num=3
            ;;
        *)
            num=
    esac
    if [ -n "$num" ]; then
        bspc monitor $monitor -n "$num" -d "$num"/{1,2,3,4,5}
    else
        bspc monitor $monitor -d {1,2,3,4,5}
    fi
    #bspc monitor $monitor -n "$i" -d {i,ii,iii,iv,v}
    let i++
done
NMON=$i
unset i

bspc rule -a Gimp desktop=^8 follow=on floating=on

# startup programs
~/.config/bspwm/startup.sh
